;;;; TANGLED WEB FROM "asdf-operations.clw". DO NOT EDIT.
#+ALLEGRO
(EVAL-WHEN (:COMPILE-TOPLEVEL :LOAD-TOPLEVEL)
  (SETQ EXCL:*SOURCE-PATHNAME* #P"asdf-operations.clw"))

(DEFPACKAGE "CLWEB/ASDF"
  (:USE "COMMON-LISP" "CLWEB" "ASDF"))
(IN-PACKAGE "CLWEB/ASDF")
(DEFCLASS CLWEB-FILE (SOURCE-FILE)
          ((TYPE :INITFORM (PATHNAME-TYPE *WEB-SOURCE-DEFAULTS*))))
(DEFMETHOD COMPONENT-PATHNAME ((COMPONENT CLWEB-FILE))
  (INPUT-FILE-PATHNAME (CALL-NEXT-METHOD)))
(DEFMETHOD OUTPUT-FILES ((OP COMPILE-OP) (COMPONENT CLWEB-FILE))
  (VALUES
   (MULTIPLE-VALUE-LIST (TANGLE-FILE-PATHNAMES (COMPONENT-PATHNAME COMPONENT)))
   NIL))
(DEFMETHOD PERFORM ((OP COMPILE-OP) (COMPONENT CLWEB-FILE))
  (TANGLE-FILE (COMPONENT-PATHNAME COMPONENT) :OUTPUT-FILE
               (FIRST (OUTPUT-FILES OP COMPONENT))))
(DEFMETHOD PERFORM ((OP LOAD-OP) (COMPONENT CLWEB-FILE))
  (MAP NIL #'LOAD
       (REMOVE-IF
        (LAMBDA (FILE)
          (STRING= (PATHNAME-TYPE FILE)
                   (PATHNAME-TYPE *LISP-SOURCE-DEFAULTS*)))
        (INPUT-FILES OP COMPONENT))))
(DEFMETHOD PERFORM ((OP LOAD-SOURCE-OP) (COMPONENT CLWEB-FILE))
  (LOAD-WEB (COMPONENT-PATHNAME COMPONENT)))
(DEFCLASS WEAVE-OP (DOWNWARD-OPERATION) NIL)
(DEFMETHOD OUTPUT-FILES ((OP WEAVE-OP) (COMPONENT CLWEB-FILE))
  (VALUES
   (MULTIPLE-VALUE-LIST (WEAVE-PATHNAMES (COMPONENT-PATHNAME COMPONENT))) T))
(DEFMETHOD PERFORM ((OP WEAVE-OP) (COMPONENT CLWEB-FILE))
  (WEAVE (COMPONENT-PATHNAME COMPONENT)))